/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __jarmadeus_I2Ctalker__
#define __jarmadeus_I2Ctalker__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jchar JNICALL Java_jarmadeus_I2Ctalker_i2cread (JNIEnv *env, jobject, jchar, jchar);
JNIEXPORT jint JNICALL Java_jarmadeus_I2Ctalker_i2cwrite (JNIEnv *env, jobject, jchar, jchar, jchar);
JNIEXPORT jchar JNICALL Java_jarmadeus_I2Ctalker_i2creadDBG (JNIEnv *env, jobject, jchar, jchar);
JNIEXPORT jint JNICALL Java_jarmadeus_I2Ctalker_i2cwriteDBG (JNIEnv *env, jobject, jchar, jchar, jchar);

#ifdef __cplusplus
}
#endif

#endif /* __jarmadeus_I2Ctalker__ */
