/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __jarmadeus_FPGATalker__
#define __jarmadeus_FPGATalker__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jchar JNICALL Java_jarmadeus_FPGATalker_fpgareadU16 (JNIEnv *env, jobject, jchar, jboolean);
JNIEXPORT jint JNICALL Java_jarmadeus_FPGATalker_fpgawriteU16 (JNIEnv *env, jobject, jchar, jchar, jboolean);
JNIEXPORT jshort JNICALL Java_jarmadeus_FPGATalker_fpgareadS16 (JNIEnv *env, jobject, jchar, jboolean);

#ifdef __cplusplus
}
#endif

#endif /* __jarmadeus_FPGATalker__ */
