/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __jarmadeus_I2CTalker__
#define __jarmadeus_I2CTalker__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jchar JNICALL Java_jarmadeus_I2CTalker_i2cread (JNIEnv *env, jobject, jchar, jchar, jboolean);
JNIEXPORT jint JNICALL Java_jarmadeus_I2CTalker_i2cwrite (JNIEnv *env, jobject, jchar, jchar, jchar, jboolean);

#ifdef __cplusplus
}
#endif

#endif /* __jarmadeus_I2CTalker__ */
